config/routes.rb
Rails.application.routes.draw do

  resources :serverspec_reports
  constraints(:id => /[^\/]+/) do
    resources :hosts do
      constraints(:host_id => /[^\/]+/) do
        resources :serverspec_reports, :only => [:index, :show]
      end
    end
  end

  namespace :api do
    scope "(:apiv)", :module => :v2, :defaults => {:apiv => 'v2'},
          :apiv => /v1|v2/, :constraints => ApiConstraints.new(:version => 2) do
      namespace :tests do

        resources :serverspec_reports, :except => [:new, :edit]
        post 'reports/', :to => 'serverspec#create'
        get  'serverspec_reports/', :to => 'serverspec#index'
      end
    end
  end
end

app/models/concerns/foreman_serverspec/host_extensions.rb
module ForemanServerspec
  module HostExtensions
    extend ActiveSupport::Concern

    included do
      has_one :serverspec_status_object, :class_name => 'HostStatus::ServerspecStatus', :foreign_key => 'host_id'

      scoped_search :in => :serverspec_status_object, :on => :status, :rename => :'serverspec_status',
               :complete_value => { :passed => HostStatus::ServerspecStatus::PASSED,
                                    :failed => HostStatus::ServerspecStatus::FAILED }
    end

    def serverspec_status(options = {})
      @serverspec_status ||= get_status(HostStatus::ServerspecStatus).to_status(options)
    end

    def serverspec_status_label(options = {})
      @serverspec_status_label ||= get_status(HostStatus::ServerspecStatus).to_label(options)
    end
  end
end

app/models/concerns/foreman_serverspec/report_extensions.rb
module ForemanServerspec
  module ReportExtensions
    extend ActiveSupport::Concern

    included do
      has_many :examples
    end
  end
end

app/models/example.rb
class Example < ActiveRecord::Base
    belongs_to :report

    validates :report_id, :status_id, :full_description, :presence => true

    LEVELS = [ 'passed', 'pending', 'failed' ]

    def status=(l)
      write_attribute(:status_id, LEVELS.index(l))
    end

    def status
      LEVELS[status_id]
    end
end

app/models/host_status/serverspec_status.rb
class HostStatus::ServerspecStatus < ::HostStatus::Status
  PASSED = 0
  FAILED = 1

  def self.status_name
    N_('Serverspec')
  end

  def self.bit_mask(status)
    "#{ServerspecReport::BIT_NUM * ServerspecReport::METRIC.index(status)} & #{ServerspecReport::MAX}"
  end

  def to_label(options = {})
    case to_status
    when PASSED
      N_('Serverspec passed')
    when FAILED
      N_('Serverspec failed')
    else
      N_('Unknown Serverspec status')
    end
  end

  def to_global(options = {})
    case to_status
    when PASSED
      ::HostStatus::Global::OK
    else
      ::HostStatus::Global::ERROR
    end
  end

  def relevant?(options = {})
    return false
  end

  def to_status(options = {})
    latest_reports = host.last_serverspec_report
    return FAILED if latest_reports.any?(&:failed?)
    PASSED
  end
end

app/models/serverspec_report.rb
class ServerspecReport < Report
  METRIC = %w[example_count failure_count pending_count]
  BIT_NUM = 10
  MAX = (1 << BIT_NUM) -1 # maximum value per metric

  #has_many :examples
  
  class << self
    delegate :model_name, :to => :superclass
  end

  def self.import(report, proxy_id = nil)
    ServerspecReportImporter.import(report, proxy_id)
  end

  # report status table column name
  def self.report_status_column
    "status"
  end

  # a method that save the report values (e.g. values from METRIC)
  # it is not supported to edit status values after it has been written once.
  def status=(st)
    s = case st
          when Integer, Fixnum
            st
          when Hash
            ServerspecReportStatusCalculator.new(:counters => st).calculate
          else
            raise Foreman::Exception(N_('Unsupported report status format'))
        end
    write_attribute(:status, s)
  end

  def summary_status
    return _("Failed") if error?
    _("Success")
  end

  delegate :error?, :changes?, :pending?, :status, :status_of, :to => :calculator
  delegate(*METRIC, :to => :calculator)

  def calculator
    ServerspecReportStatusCalculator.new(:bit_field => read_attribute(self.class.report_status_column))
  end
end

app/controllers/foreman_serverspec/hosts_controller.rb
module ForemanServerspec
  # Example: Plugin's HostsController inherits from Foreman's HostsController
  class HostsController < ::HostsController
    # change layout if needed
    # layout 'foreman_serverspec/layouts/new_layout'

    def new_action
      # automatically renders view/foreman_serverspec/hosts/new_action
    end
  end
end

app/controllers/serverspec_reports_controller.rb
class ServerspecReportsController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch

  before_action :setup_search_options, :only => :index

  def index
    @serverspec_reports = resource_base_search_and_page(:host)
  end

  def show
    # are we searching for the last report?
    if params[:id] == "last"
      conditions = { :host_id => resource_finder(Host.authorized(:view_hosts), params[:host_id]).try(:id) } if params[:host_id].present?
      params[:id] = resource_base.where(conditions).maximum(:id)
    end

    return not_found if params[:id].blank?

    @serverspec_report = resource_base.includes(:logs => [:message, :source]).find(params[:id])
    @offset = @serverspec_report.reported_at - @serverspec_report.created_at
  end

  def destroy
    @serverspec_report = resource_base.find(params[:id])
    if @serverspec_report.destroy
      process_success(:success_msg => _("Successfully deleted Serverspec report."), :success_redirect => serverspec_reports_path)
    else
      process_error
    end
  end

  private

  def resource_base
    super.my_reports
  end
end

app/helpers/serverspec_reports_helper.rb
module ServerspecReportsHelper
  def serverspec_reported_at_column(record)
    link_to(_("%s ago") % time_ago_in_words(record.reported_at), serverspec_report_path(record))
  end

  def examples_show
    return unless @serverspec_report.examples.size > 0
    form_tag serverspec_report_path(@serverspec_report), :id => 'level_filter', :method => :get, :class => "form form-horizontal" do
      content_tag(:span, _("Show examples:") + ' ') +
        select(nil, 'level', [[_('All examples'), 'info'],[_('Passed'), 'passed'],[_('Pending'), 'pending'],[_('Failures'), 'failed']],
               {}, {:class=>"col-md-1 form-control", :onchange =>"filter_by_speclevel(this);"})
    end
  end

  def status_tag(level)
    tag = case level
          when 'passed'
            "info"
          when 'failed'
            "danger"
          else
            "default"
          end
    "class='label label-#{tag}'".html_safe
  end

end

app/views/dashboard/_foreman_serverspec_widget.html.erb
<h4 class="header ca"><%= _('ForemanServerspec') %></h4>
<%= _('Widget content') %>

app/views/serverspec_reports/_list.html.erb
<table class="<%= table_css_classes('table-fixed') %>">
  <thead>
    <tr>
      <% unless params[:host_id] %>
      <th><%= sort :host, :as => _("Host") %></th>
      <% end %>
      <th><%= sort :reported, :as => _("Last report") %></th>
      <th class="col-md-1"><%= sort :examples, :as => _("Examples") %></th>
      <th class="col-md-1"><%= sort :failure, :as => _("Failed") %></th>
      <th class="col-md-1"><%= sort :pending, :as => _("Pending") %></th>
      <th class="col-md-1"><%= _('Actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% for report in @serverspec_reports %>
      <tr>
        <% if params[:host_id].nil? %>
          <% if report.host.nil? %>
              <td></td>
          <% else %>
	  <!--
	  <td class="ellipsis"><%= report.host %></td>
	  -->
          <td class="ellipsis"><%= link_to report.host, host_serverspec_reports_path(report.host) %></td>
          <% end %>
        <% end %>
        <td><%= serverspec_reported_at_column(report) %></td>
        <td><%= report_event_column(report.example_count, "label-info") %></td>
        <td><%= report_event_column(report.failure_count, "label-danger") %></td>
        <td><%= report_event_column(report.pending_count, "label-default") %></td>
        <td>
          <%= action_buttons(display_delete_if_authorized hash_for_serverspec_report_path(:id => report).merge(:auth_object => report, :authorizer => authorizer),
                                           :confirm => _("Delete report for %s?") % report.host.try(:name)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate_with_info @serverspec_reports %>

app/views/serverspec_reports/_metrics.html.erb
<% @totaltime = metrics.delete('total') %>
<% metrics.delete_if{ |k,v| v < 0.001 } %>
<div class="row">
  <div class="col-md-4">
    <div class="stats-well">
      <h4 class="ca" ><%= _('Report Metrics') %></h4>
      <div style="margin-top:50px;padding-bottom: 40px;">
        <%= flot_pie_chart("metrics" ,_("Report Metrics"), metrics, :class => "statistics-pie small")%>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="stats-well">
      <h4 class="ca" ><%= _('Report Status') %></h4>
      <%= flot_bar_chart("status" ,"", _("Number of Events"), status, :class => "statistics-bar")%>
    </div>
  </div>
  <div class="col-md-4">
    <table class="<%= table_css_classes %>" style="height: 398px;">
      <tbody>
        <% metrics.sort.each do |title, value|%>
          <tr>
            <td class="break-me">
              <%= title %>
            </td>
            <td>
              <%= metric value %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th><%= _("Total") %></th><th><%= metric (@totaltime || @serverspec_report.runtime) %></th>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/serverspec_reports/_output.html.erb
<table id='report_log' class="<%= table_css_classes %>">
  <thead>
    <tr>
      <th><%= _("Status") %></th>
      <th><%= _("Description") %></th>
      <th><%= _("File") %></th>
      <th><%= _("Line") %></th>
    </tr>
  </thead>
  <tbody>
    <% examples.each do |example| %>
    <tr>
      <td><span <%= status_tag example.status %>><%= h example.status %></span></td>
      <td class="break-me"><%= h example.full_description %></td>
      <td class="break-me"><%= h example.file_path %></td>
      <td class="break-me"><%= h example.line_number %></td>
      </tr>
    <% end %>
    <tr id='ntsh' <%= "style='display: none;'".html_safe if examples.size > 0%>><td colspan="3">
        <%= _("Nothing to show") %>
      </td></tr>
  </tbody>
</table>

app/views/serverspec_reports/index.html.erb
<% title _("Serverspec Reports") %>
<% title_actions documentation_button('3.5.4PuppetReports') %>
<%= render :partial => 'list' %>

app/views/serverspec_reports/show.html.erb
<%= javascript 'serverspec_reports' %>
<% title "#{@serverspec_report.host}"%>

<p class='ra'> <%= _("Reported at %s ") % @serverspec_report.reported_at %> </p>
<% if @offset > 10 %>
  <div class="alert alert-block alert-danger alert-dismissable">
    <%= alert_close %>
    <h3><%= _("Host times seems to be adrift!") %></h3>
    <%= (_("Host reported time is <em>%s</em>") % @serverspec_report.reported_at).html_safe %> <br/>
    <%= (_("Foreman report creation time is <em>%s</em>") % @serverspec_report.created_at).html_safe %> <br/>
    <%= (_("Which is an offset of <b>%s</b>") % distance_of_time_in_words(@serverspec_report.reported_at, @serverspec_report.created_at, :include_seconds => true)).html_safe %>
  </div>
<% end %>

<% content_for(:search_bar) {examples_show} %>

<%= render 'output', :examples => @serverspec_report.examples %>
<%= render 'metrics', :status => @serverspec_report.status, :metrics => @serverspec_report.metrics["time"] if @serverspec_report.metrics["time"] %>

<%= title_actions link_to(_('Back'), :back, :class => 'btn btn-default'),
  display_delete_if_authorized(hash_for_serverspec_report_path(:id => @serverspec_report), :class=> "btn btn-danger"),
  link_to(_("Host details"), @serverspec_report.host, :class => 'btn btn-default'),
  link_to(_("Other serverspec reports for this host"), host_serverspec_reports_path(@serverspec_report.host), :class => 'btn btn-default')
%>

<div id="diff-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><%= _("Diff View") %></h4>
      </div>
      <div  id="diff-modal-editor" class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= _("Close") %></button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/serverspec_reports/welcome.html.erb
<div class="blank-slate-pf">
  <div class="blank-slate-pf-icon">
    <%= icon_text("book", "", :kind => "fa") %>
  </div>
  <h1><%= _('Reports') %></h1>
  <p>
  <%= _("You don't seem to have any serverspec reports.") %></br>
  <%= _('If you wish to configure Serverspec to forward it reports to Foreman, please follow') %>
  <%= link_to _("e-mail reporting"), "http://github.com/foreman_serverspec/README.md", :rel => "external" %>.
  </p>
  <div class="blank-slate-pf-main-action">
    <%= link_to _('Documentation'), documentation_url("3.5.4PuppetReports"), :rel => 'external', :class => 'btn btn-primary btn-lg' %>
  </div>
</div>